package dev.hguedalia.proteroc;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;

import java.util.ArrayList;
import java.util.List;

public class PacienteDAO {

    private final Conexao conexao;
    private final SQLiteDatabase banco;

    public PacienteDAO(Context context) {
        conexao = new Conexao((context));
        banco = conexao.getWritableDatabase();
    }

    public List<Paciente> obterTodos() {
        List<Paciente> pacientes = new ArrayList<>();
        Cursor cursor = banco.query("paciente", new String[]{"id", "nome", "dataAtendimento", "dataNascimento", "idade", "leito", "prontuario", "diagnostico", "histOcup", "isolamento", "dataAdmissao", "fc", "fr", "spo2", "t", "pa", "dva", "sedoanalgesia", "aa", "caf", "catNasal", "canNasal", "mascaraVenturi", "elmo", "tot", "tqt", "glg", "rass", "las", "bo", "ashw", "asia", "bps", "hemoglobina", "leucocitos", "plaquetas", "tvp", "tep", "aptoMob", "decDorsal", "decLateral", "sed", "bip", "auM", "auRg", "auRa", "auV", "auRec", "auNat", "auTemp", "auResp", "olAs", "olAf", "olRec", "olNat", "olTemp", "olResp", "viFei", "viFee", "viFai", "viFae", "viRec", "viNat", "viTemp", "viResp", "taTl", "taTp", "taStf", "taStq", "taTr", "taEr", "taIec", "taRec", "taNat", "taTemp", "taResp", "prMal", "prMaa", "prMpa", "prCc", "prP", "prEstb", "prV", "prRec", "prNat", "prTemp", "prResp", "cgS", "cgE", "cgM", "cgRec", "cgNat", "cgTemp", "cgResp", "roo", "bbt", "kbt", "emc", "ise", "frk", "jcb", "am", "cc", "cna", "ddor"},
                null, null, null, null, "leito ASC, dataAtendimento DESC");
        while (cursor.moveToNext()) {
            Paciente p = new Paciente();
            p.setId(cursor.getInt(0));
            p.setNome(cursor.getString(1));
            p.setDataAtendimento(cursor.getString(2));
            p.setDataNascimento(cursor.getString(3));
            p.setIdade(cursor.getString(4));
            p.setLeito(cursor.getString(5));
            p.setProntuario(cursor.getString(6));
            p.setDiagnostico(cursor.getString(7));
            p.setHistOcup(cursor.getString(8));
            p.setIsolamento(cursor.getString(9));
            p.setDataAdmissao(cursor.getString(10));
            p.setFc(cursor.getString(11));
            p.setFr(cursor.getString(12));
            p.setSpo2(cursor.getString(13));
            p.setT(cursor.getString(14));
            p.setPa(cursor.getString(15));
            p.setDva(cursor.getString(16));
            p.setSedoanalgesia(cursor.getString(17));
            p.setAa(cursor.getString(18));
            p.setCaf(cursor.getString(19));
            p.setCatNasal(cursor.getString(20));
            p.setCanNasal(cursor.getString(21));
            p.setMascaraVenturi(cursor.getString(22));
            p.setElmo(cursor.getString(23));
            p.setTot(cursor.getString(24));
            p.setTqt(cursor.getString(25));
            p.setGlg(cursor.getString(26));
            p.setRass(cursor.getString(27));
            p.setLas(cursor.getString(28));
            p.setBo(cursor.getString(29));
            p.setAshw(cursor.getString(30));
            p.setAsia(cursor.getString(31));
            p.setBps(cursor.getString(32));
            p.setHemoglobina(cursor.getString(33));
            p.setLeucocitos(cursor.getString(34));
            p.setPlaquetas(cursor.getString(35));
            p.setTvp(cursor.getString(36));
            p.setTep(cursor.getString(37));
            p.setAptoMob(cursor.getString(38));
            p.setDecDorsal(cursor.getString(39));
            p.setDecLateral(cursor.getString(40));
            p.setSed(cursor.getString(41));
            p.setBip(cursor.getString(42));
            p.setAuM(cursor.getString(43));
            p.setAuRg(cursor.getString(44));
            p.setAuRa(cursor.getString(45));
            p.setAuV(cursor.getString(46));
            p.setAuRec(cursor.getString(47));
            p.setAuNat(cursor.getString(48));
            p.setAuTemp(cursor.getString(49));
            p.setAuResp(cursor.getString(50));
            p.setOlAs(cursor.getString(51));
            p.setOlAf(cursor.getString(52));
            p.setOlRec(cursor.getString(53));
            p.setOlNat(cursor.getString(54));
            p.setOlTemp(cursor.getString(55));
            p.setOlResp(cursor.getString(56));
            p.setViFei(cursor.getString(57));
            p.setViFee(cursor.getString(58));
            p.setViFai(cursor.getString(59));
            p.setViFae(cursor.getString(60));
            p.setViRec(cursor.getString(61));
            p.setViNat(cursor.getString(62));
            p.setViTemp(cursor.getString(63));
            p.setViResp(cursor.getString(64));
            p.setTaTl(cursor.getString(65));
            p.setTaTp(cursor.getString(66));
            p.setTaStf(cursor.getString(67));
            p.setTaStq(cursor.getString(68));
            p.setTaTr(cursor.getString(69));
            p.setTaEr(cursor.getString(70));
            p.setTaIec(cursor.getString(71));
            p.setTaRec(cursor.getString(72));
            p.setTaNat(cursor.getString(73));
            p.setTaTemp(cursor.getString(74));
            p.setTaResp(cursor.getString(75));
            p.setPrMal(cursor.getString(76));
            p.setPrMaa(cursor.getString(77));
            p.setPrMpa(cursor.getString(78));
            p.setPrCc(cursor.getString(79));
            p.setPrP(cursor.getString(80));
            p.setPrEstb(cursor.getString(81));
            p.setPrV(cursor.getString(82));
            p.setPrRec(cursor.getString(83));
            p.setPrNat(cursor.getString(84));
            p.setPrTemp(cursor.getString(85));
            p.setPrResp(cursor.getString(86));
            p.setCgS(cursor.getString(87));
            p.setCgE(cursor.getString(88));
            p.setCgM(cursor.getString(89));
            p.setCgRec(cursor.getString(90));
            p.setCgNat(cursor.getString(91));
            p.setCgTemp(cursor.getString(92));
            p.setCgResp(cursor.getString(93));
            p.setRoo(cursor.getString(94));
            p.setBbt(cursor.getString(95));
            p.setKbt(cursor.getString(96));
            p.setEmc(cursor.getString(97));
            p.setIse(cursor.getString(98));
            p.setFrk(cursor.getString(99));
            p.setJcb(cursor.getString(100));
            p.setAm(cursor.getString(101));
            p.setCc(cursor.getString(102));
            p.setCna(cursor.getString(103));
            p.setDdor(cursor.getString(104));
            pacientes.add(p);
        }
        return pacientes;
    }

    public List<Paciente> obterFicha() {
        List<Paciente> pacienteFicha = new ArrayList<>();
        Cursor cursor = banco.query("paciente", new String[]{"id", "nome", "dataNascimento", "idade", "leito", "prontuario", "diagnostico", "histOcup", "isolamento", "dataAdmissao"},
                null, null, null, null, "leito ASC, dataAtendimento DESC");
        while (cursor.moveToNext()) {
            Paciente p = new Paciente();
            p.setId(cursor.getInt(0));
            p.setNome(cursor.getString(1));
            p.setDataNascimento(cursor.getString(2));
            p.setIdade(cursor.getString(3));
            p.setLeito(cursor.getString(4));
            p.setProntuario(cursor.getString(5));
            p.setDiagnostico(cursor.getString(6));
            p.setHistOcup(cursor.getString(7));
            p.setIsolamento(cursor.getString(8));
            p.setDataAdmissao(cursor.getString(9));
            pacienteFicha.add(p);
        }

        return pacienteFicha;

    }

    public Paciente obterPacientePorId(int id) {
        Cursor cursor = banco.query("paciente", new String[]{"id", "nome", "dataAtendimento", "dataNascimento", "idade", "leito", "prontuario", "diagnostico", "histOcup", "isolamento", "dataAdmissao", "fc", "fr", "spo2", "t", "pa", "dva", "sedoanalgesia", "aa", "caf", "catNasal", "canNasal", "mascaraVenturi", "elmo", "tot", "tqt", "glg", "rass", "las", "bo", "ashw", "asia", "bps", "hemoglobina", "leucocitos", "plaquetas", "tvp", "tep", "aptoMob", "decDorsal", "decLateral", "sed", "bip", "auM", "auRg", "auRa", "auV", "auRec", "auNat", "auTemp", "auResp", "olAs", "olAf", "olRec", "olNat", "olTemp", "olResp", "viFei", "viFee", "viFai", "viFae", "viRec", "viNat", "viTemp", "viResp", "taTl", "taTp", "taStf", "taStq", "taTr", "taEr", "taIec", "taRec", "taNat", "taTemp", "taResp", "prMal", "prMaa", "prMpa", "prCc", "prP", "prEstb", "prV", "prRec", "prNat", "prTemp", "prResp", "cgS", "cgE", "cgM", "cgRec", "cgNat", "cgTemp", "cgResp", "roo", "bbt", "kbt", "emc", "ise", "frk", "jcb", "am", "cc", "cna", "ddor"},
                "id = ?", new String[]{String.valueOf(id)}, null, null, null);
        if (cursor.moveToFirst()) {
            Paciente p = new Paciente();
            p.setId(cursor.getInt(0));
            p.setNome(cursor.getString(1));
            p.setDataAtendimento(cursor.getString(2));
            p.setDataNascimento(cursor.getString(3));
            p.setIdade(cursor.getString(4));
            p.setLeito(cursor.getString(5));
            p.setProntuario(cursor.getString(6));
            p.setDiagnostico(cursor.getString(7));
            p.setHistOcup(cursor.getString(8));
            p.setIsolamento(cursor.getString(9));
            p.setDataAdmissao(cursor.getString(10));
            p.setFc(cursor.getString(11));
            p.setFr(cursor.getString(12));
            p.setSpo2(cursor.getString(13));
            p.setT(cursor.getString(14));
            p.setPa(cursor.getString(15));
            p.setDva(cursor.getString(16));
            p.setSedoanalgesia(cursor.getString(17));
            p.setAa(cursor.getString(18));
            p.setCaf(cursor.getString(19));
            p.setCatNasal(cursor.getString(20));
            p.setCanNasal(cursor.getString(21));
            p.setMascaraVenturi(cursor.getString(22));
            p.setElmo(cursor.getString(23));
            p.setTot(cursor.getString(24));
            p.setTqt(cursor.getString(25));
            p.setGlg(cursor.getString(26));
            p.setRass(cursor.getString(27));
            p.setLas(cursor.getString(28));
            p.setBo(cursor.getString(29));
            p.setAshw(cursor.getString(30));
            p.setAsia(cursor.getString(31));
            p.setBps(cursor.getString(32));
            p.setHemoglobina(cursor.getString(33));
            p.setLeucocitos(cursor.getString(34));
            p.setPlaquetas(cursor.getString(35));
            p.setTvp(cursor.getString(36));
            p.setTep(cursor.getString(37));
            p.setAptoMob(cursor.getString(38));
            p.setDecDorsal(cursor.getString(39));
            p.setDecLateral(cursor.getString(40));
            p.setSed(cursor.getString(41));
            p.setBip(cursor.getString(42));
            p.setAuM(cursor.getString(43));
            p.setAuRg(cursor.getString(44));
            p.setAuRa(cursor.getString(45));
            p.setAuV(cursor.getString(46));
            p.setAuRec(cursor.getString(47));
            p.setAuNat(cursor.getString(48));
            p.setAuTemp(cursor.getString(49));
            p.setAuResp(cursor.getString(50));
            p.setOlAs(cursor.getString(51));
            p.setOlAf(cursor.getString(52));
            p.setOlRec(cursor.getString(53));
            p.setOlNat(cursor.getString(54));
            p.setOlTemp(cursor.getString(55));
            p.setOlResp(cursor.getString(56));
            p.setViFei(cursor.getString(57));
            p.setViFee(cursor.getString(58));
            p.setViFai(cursor.getString(59));
            p.setViFae(cursor.getString(60));
            p.setViRec(cursor.getString(61));
            p.setViNat(cursor.getString(62));
            p.setViTemp(cursor.getString(63));
            p.setViResp(cursor.getString(64));
            p.setTaTl(cursor.getString(65));
            p.setTaTp(cursor.getString(66));
            p.setTaStf(cursor.getString(67));
            p.setTaStq(cursor.getString(68));
            p.setTaTr(cursor.getString(69));
            p.setTaEr(cursor.getString(70));
            p.setTaIec(cursor.getString(71));
            p.setTaRec(cursor.getString(72));
            p.setTaNat(cursor.getString(73));
            p.setTaTemp(cursor.getString(74));
            p.setTaResp(cursor.getString(75));
            p.setPrMal(cursor.getString(76));
            p.setPrMaa(cursor.getString(77));
            p.setPrMpa(cursor.getString(78));
            p.setPrCc(cursor.getString(79));
            p.setPrP(cursor.getString(80));
            p.setPrEstb(cursor.getString(81));
            p.setPrV(cursor.getString(82));
            p.setPrRec(cursor.getString(83));
            p.setPrNat(cursor.getString(84));
            p.setPrTemp(cursor.getString(85));
            p.setPrResp(cursor.getString(86));
            p.setCgS(cursor.getString(87));
            p.setCgE(cursor.getString(88));
            p.setCgM(cursor.getString(89));
            p.setCgRec(cursor.getString(90));
            p.setCgNat(cursor.getString(91));
            p.setCgTemp(cursor.getString(92));
            p.setCgResp(cursor.getString(93));
            p.setRoo(cursor.getString(94));
            p.setBbt(cursor.getString(95));
            p.setKbt(cursor.getString(96));
            p.setEmc(cursor.getString(97));
            p.setIse(cursor.getString(98));
            p.setFrk(cursor.getString(99));
            p.setJcb(cursor.getString(100));
            p.setAm(cursor.getString(101));
            p.setCc(cursor.getString(102));
            p.setCna(cursor.getString(103));
            p.setDdor(cursor.getString(104));
            return p;
        }
        return null;
    }

    public long inserir(Paciente paciente) {
        ContentValues values = new ContentValues();
        values.put("nome", paciente.getNome());
        values.put("dataAtendimento", paciente.getDataAtendimento());
        values.put("dataNascimento", paciente.getDataNascimento());
        values.put("idade", paciente.getIdade());
        values.put("leito", paciente.getLeito());
        values.put("prontuario", paciente.getProntuario());
        values.put("diagnostico", paciente.getDiagnostico());
        values.put("histOcup", paciente.getHistOcup());
        values.put("isolamento", paciente.getIsolamento());
        values.put("dataAdmissao", paciente.getDataAdmissao());
        values.put("fc", paciente.getFc());
        values.put("fr", paciente.getFr());
        values.put("spo2", paciente.getSpo2());
        values.put("t", paciente.getT());
        values.put("pa", paciente.getPa());
        values.put("dva", paciente.getDva());
        values.put("sedoanalgesia", paciente.getSedoanalgesia());
        values.put("aa", paciente.getAa());
        values.put("caf", paciente.getCaf());
        values.put("catNasal", paciente.getCatNasal());
        values.put("canNasal", paciente.getCanNasal());
        values.put("mascaraVenturi", paciente.getMascaraVenturi());
        values.put("elmo", paciente.getElmo());
        values.put("tot", paciente.getTot());
        values.put("tqt", paciente.getTqt());
        values.put("glg", paciente.getGlg());
        values.put("rass", paciente.getRass());
        values.put("las", paciente.getLas());
        values.put("bo", paciente.getBo());
        values.put("ashw", paciente.getAshw());
        values.put("asia", paciente.getAsia());
        values.put("bps", paciente.getBps());
        values.put("hemoglobina", paciente.getHemoglobina());
        values.put("leucocitos", paciente.getLeucocitos());
        values.put("plaquetas", paciente.getPlaquetas());
        values.put("tvp", paciente.getTvp());
        values.put("tep", paciente.getTep());
        values.put("aptoMob", paciente.getAptoMob());
        values.put("decDorsal", paciente.getDecDorsal());
        values.put("decLateral", paciente.getDecLateral());
        values.put("sed", paciente.getSed());
        values.put("bip", paciente.getBip());
        values.put("auM", paciente.getAuM());
        values.put("auRg", paciente.getAuRg());
        values.put("auRa", paciente.getAuRa());
        values.put("auV", paciente.getAuV());
        values.put("auRec", paciente.getAuRec());
        values.put("auNat", paciente.getAuNat());
        values.put("auTemp", paciente.getAuTemp());
        values.put("auResp", paciente.getAuResp());
        values.put("olAs", paciente.getOlAs());
        values.put("olAf", paciente.getOlAf());
        values.put("olRec", paciente.getOlRec());
        values.put("olNat", paciente.getOlNat());
        values.put("olTemp", paciente.getOlTemp());
        values.put("olResp", paciente.getOlResp());
        values.put("viFei", paciente.getViFei());
        values.put("viFee", paciente.getViFee());
        values.put("viFai", paciente.getViFai());
        values.put("viFae", paciente.getViFae());
        values.put("viRec", paciente.getViRec());
        values.put("viNat", paciente.getViNat());
        values.put("viTemp", paciente.getViTemp());
        values.put("viResp", paciente.getViResp());
        values.put("taTl", paciente.getTaTl());
        values.put("taTp", paciente.getTaTp());
        values.put("taStf", paciente.getTaStf());
        values.put("taStq", paciente.getTaStq());
        values.put("taTr", paciente.getTaTr());
        values.put("taEr", paciente.getTaEr());
        values.put("taIec", paciente.getTaIec());
        values.put("taRec", paciente.getTaRec());
        values.put("taNat", paciente.getTaNat());
        values.put("taTemp", paciente.getTaTemp());
        values.put("taResp", paciente.getTaResp());
        values.put("prMal", paciente.getPrMal());
        values.put("prMaa", paciente.getPrMaa());
        values.put("prMpa", paciente.getPrMpa());
        values.put("prCc", paciente.getPrCc());
        values.put("prP", paciente.getPrP());
        values.put("prEstb", paciente.getPrEstb());
        values.put("prV", paciente.getPrV());
        values.put("prRec", paciente.getPrRec());
        values.put("prNat", paciente.getPrNat());
        values.put("prTemp", paciente.getPrTemp());
        values.put("prResp", paciente.getPrResp());
        values.put("cgS", paciente.getCgS());
        values.put("cgE", paciente.getCgE());
        values.put("cgM", paciente.getCgM());
        values.put("cgRec", paciente.getCgRec());
        values.put("cgNat", paciente.getCgNat());
        values.put("cgTemp", paciente.getCgTemp());
        values.put("cgResp", paciente.getCgResp());
        values.put("roo", paciente.getRoo());
        values.put("bbt", paciente.getBbt());
        values.put("kbt", paciente.getKbt());
        values.put("emc", paciente.getEmc());
        values.put("ise", paciente.getIse());
        values.put("frk", paciente.getFrk());
        values.put("jcb", paciente.getJcb());
        values.put("am", paciente.getAm());
        values.put("cc", paciente.getCc());
        values.put("cna", paciente.getCna());
        values.put("ddor", paciente.getDdor());
        return banco.insert("paciente", null, values);
    }

    public void excluir(Paciente p) {
        banco.delete("paciente", "id = ?", new String[]{p.getId().toString()});
    }

    public void atualizar(Paciente paciente) {
        ContentValues values = new ContentValues();
        values.put("nome", paciente.getNome());
        values.put("dataAtendimento", paciente.getDataAtendimento());
        values.put("dataNascimento", paciente.getDataNascimento());
        values.put("idade", paciente.getIdade());
        values.put("leito", paciente.getLeito());
        values.put("prontuario", paciente.getProntuario());
        values.put("diagnostico", paciente.getDiagnostico());
        values.put("histOcup", paciente.getHistOcup());
        values.put("isolamento", paciente.getIsolamento());
        values.put("dataAdmissao", paciente.getDataAdmissao());
        values.put("fc", paciente.getFc());
        values.put("fr", paciente.getFr());
        values.put("spo2", paciente.getSpo2());
        values.put("t", paciente.getT());
        values.put("pa", paciente.getPa());
        values.put("dva", paciente.getDva());
        values.put("sedoanalgesia", paciente.getSedoanalgesia());
        values.put("aa", paciente.getAa());
        values.put("caf", paciente.getCaf());
        values.put("catNasal", paciente.getCatNasal());
        values.put("canNasal", paciente.getCanNasal());
        values.put("mascaraVenturi", paciente.getMascaraVenturi());
        values.put("elmo", paciente.getElmo());
        values.put("tot", paciente.getTot());
        values.put("tqt", paciente.getTqt());
        values.put("glg", paciente.getGlg());
        values.put("rass", paciente.getRass());
        values.put("las", paciente.getLas());
        values.put("bo", paciente.getBo());
        values.put("ashw", paciente.getAshw());
        values.put("asia", paciente.getAsia());
        values.put("bps", paciente.getBps());
        values.put("hemoglobina", paciente.getHemoglobina());
        values.put("leucocitos", paciente.getLeucocitos());
        values.put("plaquetas", paciente.getPlaquetas());
        values.put("tvp", paciente.getTvp());
        values.put("tep", paciente.getTep());
        values.put("aptoMob", paciente.getAptoMob());
        values.put("decDorsal", paciente.getDecDorsal());
        values.put("decLateral", paciente.getDecLateral());
        values.put("sed", paciente.getSed());
        values.put("bip", paciente.getBip());
        values.put("auM", paciente.getAuM());
        values.put("auRg", paciente.getAuRg());
        values.put("auRa", paciente.getAuRa());
        values.put("auV", paciente.getAuV());
        values.put("auRec", paciente.getAuRec());
        values.put("auNat", paciente.getAuNat());
        values.put("auTemp", paciente.getAuTemp());
        values.put("auResp", paciente.getAuResp());
        values.put("olAs", paciente.getOlAs());
        values.put("olAf", paciente.getOlAf());
        values.put("olRec", paciente.getOlRec());
        values.put("olNat", paciente.getOlNat());
        values.put("olTemp", paciente.getOlTemp());
        values.put("olResp", paciente.getOlResp());
        values.put("viFei", paciente.getViFei());
        values.put("viFee", paciente.getViFee());
        values.put("viFai", paciente.getViFai());
        values.put("viFae", paciente.getViFae());
        values.put("viRec", paciente.getViRec());
        values.put("viNat", paciente.getViNat());
        values.put("viTemp", paciente.getViTemp());
        values.put("viResp", paciente.getViResp());
        values.put("taTl", paciente.getTaTl());
        values.put("taTp", paciente.getTaTp());
        values.put("taStf", paciente.getTaStf());
        values.put("taStq", paciente.getTaStq());
        values.put("taTr", paciente.getTaTr());
        values.put("taEr", paciente.getTaEr());
        values.put("taIec", paciente.getTaIec());
        values.put("taRec", paciente.getTaRec());
        values.put("taNat", paciente.getTaNat());
        values.put("taTemp", paciente.getTaTemp());
        values.put("taResp", paciente.getTaResp());
        values.put("prMal", paciente.getPrMal());
        values.put("prMaa", paciente.getPrMaa());
        values.put("prMpa", paciente.getPrMpa());
        values.put("prCc", paciente.getPrCc());
        values.put("prP", paciente.getPrP());
        values.put("prEstb", paciente.getPrEstb());
        values.put("prV", paciente.getPrV());
        values.put("prRec", paciente.getPrRec());
        values.put("prNat", paciente.getPrNat());
        values.put("prTemp", paciente.getPrTemp());
        values.put("prResp", paciente.getPrResp());
        values.put("cgS", paciente.getCgS());
        values.put("cgE", paciente.getCgE());
        values.put("cgM", paciente.getCgM());
        values.put("cgRec", paciente.getCgRec());
        values.put("cgNat", paciente.getCgNat());
        values.put("cgTemp", paciente.getCgTemp());
        values.put("cgResp", paciente.getCgResp());
        values.put("roo", paciente.getRoo());
        values.put("bbt", paciente.getBbt());
        values.put("kbt", paciente.getKbt());
        values.put("emc", paciente.getEmc());
        values.put("ise", paciente.getIse());
        values.put("frk", paciente.getFrk());
        values.put("jcb", paciente.getJcb());
        values.put("am", paciente.getAm());
        values.put("cc", paciente.getCc());
        values.put("cna", paciente.getCna());
        values.put("ddor", paciente.getDdor());
        banco.update("paciente", values, "id = ?", new String[]{paciente.getId().toString()});
    }

}
